### ISSUE TITLE
Conda installation not working

### ISSUE THREAD

**Issue by michelelucente** [astrolamb/ceffyl#25]
Hi, the `conda` installation does not currently work. Here is the output of `conda install -c conda-forge ceffyl`:

```
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - ceffyl

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by astrolamb** [comment]
Hi @michelelucente , thanks for your message. That is very unusual. I just tried `conda install -c conda-forge ceffyl` in a new conda environment and I don't have this problem.

Please try it again. If it doesn't work, send me the specs of your conda environment e.g. python version, and your machine specifications.

**Comment by astrolamb** [comment]
Hi @michelelucente , I believe I may have found the bug.

Did you create a new conda environment from scratch, and then try to install ceffyl?

It turns out a dependency, TEMPO2, could be at fault. To get a working installation, please first install TEMPO2/libstempo via enterprise
`conda install -c conda-forge enterprise-pulsar`

After this, you may install ceffyl:
`conda install -c conda-forge ceffyl`

Please let me know if this solves the problem!

**Comment by michelelucente** [comment]
Hi @astrolamb, actually I had to build TEMPO2 from source, since there is no conda package for the osx-arm64 platform.

Nevertheless, I want to confirm that the installation works fine via pip. I build TEMPO2 and then I run
``` 
pip install libstempo
pip install enterprise-pulsar
pip install ceffyl 
```

For you information, this is the output if I try to install enterprise-pulsar via conda:
```
(base) ➜  ~ conda create -n test -c conda-forge enterprise-pulsar   
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides libstempo >=2.4.0 needed by enterprise-pulsar-3.1.0-pyhd8ed1ab_0

Could not solve for environment specs
The following package could not be installed
└─ enterprise-pulsar is not installable because it requires
   └─ libstempo >=2.4.0 , which does not exist (perhaps a missing channel).
```

I think that the main issue here is that there is no tempo2/libstempo installation on conda for the osx-arm64 platform. 

From my side you can close the issue, since the pip installation works. I am nevertheless available if you need me to test something else on my platform.

Thank you!

**Comment by astrolamb** [comment]
Thank you @michelelucente for the extra info. I was made aware of the tempo2 issues over the weekend, it's been causing some headaches for the community. You may have seen that I updated some info on the front page of ceffyl.

The unfortunate thing is, ceffyl doesn't actually need tempo2! It has a dependency on some classes in enterprise, but enterprise is dependent on tempo2, so...

In the next version of ceffyl, I plan to remove the enterprise dependency.

I hope that ceffyl is easy to use for you. I'm writing up some docs currently so if you have any questions, please send me a message! If you're using this to fit NANOGrav 15-yr data, note that I updated the files over the weekend.

Thanks, William
